---
- hosts: all
  become: yes
      
  tasks:
    # Mandatory TraceCreator tasks
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install build-essential
      apt: name=build-essential state=present
    - name: Enable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication yes"
    - name: restart sshd
      service: name=ssh state=restarted

    # Other tasks specific for given job
    - name: Install nmap
      apt: name=nmap state=present
